name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
            dotnet-version: '6.0.x'

      - name: Install Dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore
